# Generated by Django 4.2.3 on 2023-07-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='deleted_at',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminarcion'),
        ),
        migrations.AlterField(
            model_name='historicalboard',
            name='deleted_at',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminarcion'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='assigne',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asignado'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='deleted_at',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminarcion'),
        ),
        migrations.AlterField(
            model_name='historicaltasklist',
            name='deleted_at',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminarcion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigne',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asignado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted_at',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminarcion'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='deleted_at',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminarcion'),
        ),
    ]
